name: Deploy Main Branch
run-name: ${{ github.actor }} is deploying to main
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3 # Community action untuk SSH
        with:
          host: ${{ secrets.HOST }} # ${{ secrets.X }} = ambil dari GitHub Secrets
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }} # Private key SSH
          script: |
            set -e

            APP_DIR=/root/tanstack
            REPO_URL=${{ github.server_url }}/${{ github.repository }}.git

            echo "==> Create app directory if not exists"
            mkdir -p $APP_DIR
            cd $APP_DIR

            if [ ! -d ".git" ]; then
              echo "==> Cloning repository"
              git clone $REPO_URL .
            else
              echo "==> Updating repository"
              git fetch origin
              git reset --hard origin/main
            fi

            echo "==> Create .env file"
            cat << 'EOF' > .env
            ${{ secrets.ENV_FILE }}
            EOF

            echo "==> Docker compose up"
            docker compose down
            docker compose pull
            docker compose -f docker-compose.prod.yml up -d
